[package]
name = "dec-cryptor"
version = "3.1.0"
edition = "2024"
license = "MIT"
authors = ["Jiafei cxkctrl1303@hotmail.com"]
description = "A high-performance file encryption tool using AES-256-CTR and Argon2id."
repository = "https://github.com/Jiafei-Queen/dec-cryptor"
readme = "README.md"
keywords = ["encryption", "aes", "parallel", "security", "argon2"]
categories = ["cryptography", "command-line-utilities"]

[[bin]]
name = "dec"
path = "src/main.rs"

[dependencies]
rpassword = "7.4.0"
rand = "0.10.0"
aes-gcm = "0.10.0"
argon2 = "0.5.3"
rayon = "1.11.0"
tempfile = "3.24.0"
generic-array = "0.14.7"
once_cell = "1.19.0"
