[package]
name = "dec"
version = "2.5.0"
edition = "2024"
license = "MIT"
authors = ["Jiafei <你的邮箱>"]
description = "A high-performance file encryption tool using AES-256-CTR and Argon2id."
repository = "https://github.com/Jiafei-Queen/dec-cryptor"
readme = "README.md"
keywords = ["encryption", "aes", "parallel", "security", "argon2"]
categories = ["cryptography", "command-line-utilities"]

[dependencies]
rpassword = "7.4.0"
rand = "0.10.0"
aes = "0.8.4"
ctr = "0.9.2"
argon2 = "0.5.3"
hmac = "0.12.1"
sha2 = "0.10.9"
hkdf = "0.12.4"
rayon = "1.11.0"
tempfile = "3.24.0"